"""update-database2

Revision ID: 535310778f91
Revises: 69b78cfde09b
Create Date: 2024-08-20 23:22:05.048195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535310778f91'
down_revision: Union[str, None] = '69b78cfde09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'age',
               existing_type=sa.Integer(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'age',
               existing_type=sa.Integer(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###
