"""create post table and update group table

Revision ID: d8e068852420
Revises: eb2bfac0f122
Create Date: 2024-08-27 22:25:37.228400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e068852420'
down_revision: Union[str, None] = 'eb2bfac0f122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('groups', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['admin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'admin_id')
    # ### end Alembic commands ###
