"""update comment table

Revision ID: faee37063672
Revises: 9b5a455b768a
Create Date: 2024-09-09 21:26:28.949204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faee37063672'
down_revision: Union[str, None] = '9b5a455b768a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('comments', 'react')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('react', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
