"""update groupmembers

Revision ID: ffa8785f4141
Revises: d9b42b37504b
Create Date: 2024-09-08 14:06:35.892585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa8785f4141'
down_revision: Union[str, None] = 'd9b42b37504b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupmembers', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.add_column('groupmembers', sa.Column('reason', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groupmembers', 'reason')
    op.drop_column('groupmembers', 'admin_id')
    # ### end Alembic commands ###
